###
GET http://192.168.137.165:5000/utilisateur?id=100

###
POST http://192.168.137.165:5000/utilisateur
Content-Type: application/json

{
    "id_util": 250,
    "mail_util": "martin@gmail.com",
    "nom_util": "Martin",
    "password": "Xg5r7d",
    "prenom_util": "John"
}

###
POST http://192.168.137.165:5000/connexion
Content-Type: application/json

{
    "mail_util": "martin@gmail.com",
    "password": "Xg5r7d"
}

###
GET http://192.168.137.165:5000/objects